import homeImg from './home.png';
import arrowImg from './arrow.png';
import plusImg from './plus.png';
import compassImg from './compass.png';
import avatarImg from './avatar.png';
import moreImg from './more.png';
import textImg from './text.png';
import loveBlackImg from './love-black.png';
import loveRedImg from './love-red.png';

export const home = homeImg;
export const arrow = arrowImg;
export const plus = plusImg;
export const compass = compassImg;
export const avatar = avatarImg;
export const more = moreImg;
export const text = textImg;
export const loveBlack = loveBlackImg;
export const loveRed = loveRedImg;
export const codestateAvatar = "https://www.codestates.com/assets/codestates-ci.png";